CREATE INDEX DbCaptureTableChange$COMPOSI0 ON DbCaptureTableChange(idA3A3)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureTableChange$COMPOSI1 ON DbCaptureTableChange(captureId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureTableChange$COMPOSI2 ON DbCaptureTableChange(captureId,tableName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
