CREATE INDEX DbCaptureSession$COMPOSITE0 ON DbCaptureSession(captureId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureSession$COMPOSITE1 ON DbCaptureSession(status)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureSession$COMPOSITE2 ON DbCaptureSession(startTime)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
