CREATE INDEX DbCaptureChange$COMPOSITE0 ON DbCaptureChange(idA3A3)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureChange$COMPOSITE1 ON DbCaptureChange(tableName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureChange$COMPOSITE2 ON DbCaptureChange(idA3A3,tableName,targetRowId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureChange$COMPOSITE3 ON DbCaptureChange(transactionId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
