CREATE INDEX DbCaptureAttrDelta$COMPOSITE0 ON DbCaptureAttrDelta(idA3A3)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureAttrDelta$COMPOSITE1 ON DbCaptureAttrDelta(captureId)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureAttrDelta$COMPOSITE2 ON DbCaptureAttrDelta(captureId,tableName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX DbCaptureAttrDelta$COMPOSITE3 ON DbCaptureAttrDelta(columnName)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
